//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_de_conge
{
    using System;
    using System.Collections.Generic;
    
    public partial class arch_conge
    {
        public int num_conge { get; set; }
        public string cin { get; set; }
        public string nature { get; set; }
        public Nullable<System.DateTime> date_d { get; set; }
        public Nullable<System.DateTime> date_f { get; set; }
        public Nullable<System.DateTime> date_demande { get; set; }
        public Nullable<int> nbr_jour { get; set; }
        public string statu { get; set; }
    }
}
