//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_de_conge
{
    using System;
    using System.Collections.Generic;
    
    public partial class arch_personne
    {
        public string cin { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public string adress { get; set; }
        public Nullable<System.DateTime> date_ns { get; set; }
        public Nullable<System.DateTime> date_rec { get; set; }
        public Nullable<int> nbr_enf { get; set; }
        public string grade { get; set; }
        public string afectation_act { get; set; }
        public string fonction_interier { get; set; }
        public string fonction_act { get; set; }
        public string situation_fa { get; set; }
        public string niveau_ins { get; set; }
        public Nullable<int> code_dip { get; set; }
        public string diplome { get; set; }
        public Nullable<int> num_service { get; set; }
        public string tel { get; set; }
    }
}
