//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_de_conge
{
    using System;
    using System.Collections.Generic;
    
    public partial class messagee
    {
        public int message_id { get; set; }
        public string cin { get; set; }
        public string message_text { get; set; }
        public string emeteur { get; set; }
        public string recepteur { get; set; }
        public Nullable<System.DateTime> date_msg { get; set; }
    
        public virtual personne personne { get; set; }
        public virtual personne personne1 { get; set; }
    }
}
