//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_de_conge
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gestion_de_congeEntities : DbContext
    {
        public gestion_de_congeEntities()
            : base("name=gestion_de_congeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<arch_conge> arch_conge { get; set; }
        public virtual DbSet<arch_personne> arch_personne { get; set; }
        public virtual DbSet<conge> conges { get; set; }
        public virtual DbSet<logine> logines { get; set; }
        public virtual DbSet<messagee> messagees { get; set; }
        public virtual DbSet<personne> personnes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
