//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_de_conge
{
    using System;
    using System.Collections.Generic;
    
    public partial class personne
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public personne()
        {
            this.conges = new HashSet<conge>();
            this.conges1 = new HashSet<conge>();
            this.logines = new HashSet<logine>();
            this.logines1 = new HashSet<logine>();
            this.messagees = new HashSet<messagee>();
            this.messagees1 = new HashSet<messagee>();
        }
    
        public string cin { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public string adress { get; set; }
        public Nullable<System.DateTime> date_ns { get; set; }
        public Nullable<System.DateTime> date_rec { get; set; }
        public Nullable<int> nbr_enf { get; set; }
        public string grade { get; set; }
        public string afectation_act { get; set; }
        public string fonction_interier { get; set; }
        public string fonction_act { get; set; }
        public string situation_fa { get; set; }
        public string niveau_ins { get; set; }
        public Nullable<int> code_dip { get; set; }
        public string diplome { get; set; }
        public Nullable<int> num_service { get; set; }
        public string tel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<conge> conges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<conge> conges1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<logine> logines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<logine> logines1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<messagee> messagees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<messagee> messagees1 { get; set; }
    }
}
